### ISSUE TITLE
Default hack is not working in default setup (using kibana tag 4.4.2)

### ISSUE THREAD

**Issue by petmakris** [elastic/generator-kibana-plugin#28]
```
server    log   [18:26:02.774] [fatal] Error: unknown export types hacks in plugin tracing
    at UiExports.consumePlugin (/Users/takeda/kibana-plugins/kibana/src/ui/UiExports.js:24:13)
    at Object.callee$0$0$ (/Users/takeda/kibana-plugins/kibana/src/ui/index.js:28:15)
    at tryCatch (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/Users/takeda/kibana-plugins/kibana/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:197:7)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at KbnServer.callee$0$0 (/Users/takeda/kibana-plugins/kibana/src/ui/index.js:62:28)
    at KbnServer.mixin$ (/Users/takeda/kibana-plugins/kibana/src/server/KbnServer.js:62:16)
    at tryCatch (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:315:22)
FATAL [Error: unknown export types hacks in plugin tracing]
optmzr    log   [18:26:02.784] [fatal] Error: unknown export types hacks in plugin tracing
    at UiExports.consumePlugin (/Users/takeda/kibana-plugins/kibana/src/ui/UiExports.js:24:13)
    at Object.callee$0$0$ (/Users/takeda/kibana-plugins/kibana/src/ui/index.js:28:15)
    at tryCatch (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/Users/takeda/kibana-plugins/kibana/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:197:7)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at KbnServer.callee$0$0 (/Users/takeda/kibana-plugins/kibana/src/ui/index.js:62:28)
    at KbnServer.mixin$ (/Users/takeda/kibana-plugins/kibana/src/server/KbnServer.js:62:16)
    at tryCatch (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/takeda/kibana-plugins/kibana/node_modules/babel-runtime/regenerator/runtime.js:315:22)
FATAL [Error: unknown export types hacks in plugin tracing]
 server crashed  with status code 1
 optimizer crashed  with status code 1
child_process.js:487
    throw err;
    ^

Error: Command failed: bin/kibana --dev --plugin-path /Users/takeda/kibana-plugins/tracing
    at checkExecSyncError (child_process.js:464:13)
    at execFileSync (child_process.js:484:13)
    at module.exports (/Users/takeda/kibana-plugins/tracing/node_modules/@elastic/plugin-helpers/tasks/start.js:9:3)
    at module.exports (/Users/takeda/kibana-plugins/tracing/node_modules/@elastic/plugin-helpers/lib/command.js:18:3)
    at Object.<anonymous> (/Users/takeda/kibana-plugins/tracing/node_modules/@elastic/plugin-helpers/bin/plugin-helpers-start.js:3:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/takeda/.nvm/versions/node/v4.3.2/bin/node" "/Users/takeda/.nvm/versions/node/v4.3.2/bin/npm" "start"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! tracing@0.0.0 start: `plugin-helpers start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tracing@0.0.0 start script 'plugin-helpers start'.
npm ERR! This is most likely a problem with the tracing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     plugin-helpers start
npm ERR! You can get their info via:
npm ERR!     npm owner ls tracing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/takeda/kibana-plugins/tracing/npm-debug.log
```

But then again if the hack is removed

```

    ERROR in ../tracing/public/app.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/takeda/kibana-plugins/kibana/src/ui/public/autoload/styles in /Users/takeda/kibana-plugins/tracing/public
     @ ../tracing/public/app.js 21:0-29

    ERROR in ../tracing/public/app.js
    Module not found: Error: Cannot resolve module 'moment' in /Users/takeda/kibana-plugins/tracing/public
     @ ../tracing/public/app.js 5:14-31
...
....
```

**Comment by veershrivastav** [comment]
Did you get any solution on this?

**Comment by hari-kris** [comment]
@petmakris I am facing same issue while running the generator. Could you please share how you solved  the issue

**Comment by phpmind** [comment]
Any solution for this mess ?

**Comment by spalger** [comment]
FYI, The plugin generator creates plugins designed to work with Kibana 5.0+

**Comment by phpmind** [comment]
spalger@ I want to have fix position of data table header. I have created code but not sure where to put in kibana 4.5. Can you please tell me where can i add my jquery custom code.
 Hacks type does not work in kibana 4.5.

**Comment by timroes** [comment]
Before Kibana 5 the `hacks` key in `uiExports` doesn't exist. As a workaround you can just replace the `hacks` key with `visTypes`. This is meant to register new visualization types, but since Kibana doesn't do anythign else (yet) than inluding this file, into the frontend, it actually doesn't matter in which of the keys you use it.

But be aware - as for everything in the plugin "API" - this might change over time. I have an [open ticket](https://github.com/elastic/kibana/issues/4676) asking to register the types automatically, which would break the above workaround if it will be implemented.
