### ISSUE TITLE
Generator plugin not starting 

### ISSUE THREAD

**Issue by hari-kris** [elastic/generator-kibana-plugin#32]
When I try to start the generator plugin after following [https://www.npmjs.com/package/generator-kibana-plugin](url) . I am getting the following error

> ./bin/kibana --dev

 watching for changes  (98 files)
optmzr    log   [11:08:57.632] [fatal] Error: unknown export types hacks in plugin my_sample_plugin
    at UiExports.consumePlugin (/home/hkrishnamoorthy/kibana-4.5/src/ui/UiExports.js:24:13)
    at Object.callee$0$0$ (/home/hkrishnamoorthy/kibana-4.5/src/ui/index.js:28:15)
    at tryCatch (/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke](/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next](/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:197:7)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next](/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at KbnServer.callee$0$0 (/home/hkrishnamoorthy/kibana-4.5/src/ui/index.js:62:28)
    at KbnServer.mixin$ (/home/hkrishnamoorthy/kibana-4.5/src/server/KbnServer.js:62:16)
    at tryCatch (/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke](/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:315:22)
FATAL [Error: unknown export types hacks in plugin my_sample_plugin]
server    log   [11:08:57.676] [fatal] Error: unknown export types hacks in plugin my_sample_plugin
    at UiExports.consumePlugin (/home/hkrishnamoorthy/kibana-4.5/src/ui/UiExports.js:24:13)
    at Object.callee$0$0$ (/home/hkrishnamoorthy/kibana-4.5/src/ui/index.js:28:15)
    at tryCatch (/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke](/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next](/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:197:7)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next](/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at KbnServer.callee$0$0 (/home/hkrishnamoorthy/kibana-4.5/src/ui/index.js:62:28)
    at KbnServer.mixin$ (/home/hkrishnamoorthy/kibana-4.5/src/server/KbnServer.js:62:16)
    at tryCatch (/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke](/home/hkrishnamoorthy/kibana-4.5/node_modules/babel-runtime/regenerator/runtime.js:315:22)
FATAL [Error: unknown export types hacks in plugin my_sample_plugin]
 optimizer crashed  with status code 1

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/home/hkrishnamoorthy/.nvm/versions/node/v4.4.4/bin/node" "/home/hkrishnamoorthy/.nvm/versions/node/v4.4.4/bin/npm" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! kibana@4.5.2-snapshot start: `./bin/kibana --dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kibana@4.5.2-snapshot start script './bin/kibana --dev'.
npm ERR! This is most likely a problem with the kibana package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/kibana --dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kibana
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls kibana
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hkrishnamoorthy/kibana-4.5/npm-debug.log

Environment
Ubuntu:16.04LTS
Kibana 4.3.X
Elastic 2.3.X

**Comment by rashidkpc** [comment]
Hack plugins require kibana 5+

**Comment by hari-kris** [comment]
@rashidkpc  Thanks for the reply. Can you please point out the right way to develop plugin in 4.5.X. Any help would be much appreciated
