### ISSUE TITLE
The kibana develop problem

### ISSUE THREAD

**Issue by LazyerHong** [elastic/generator-kibana-plugin#33]
I have applied a open source kibana app elasticsearch_status in the kibana4.2.
But when i npm start the kibana, there are some errors:

ERROR in ./installedPlugins/elasticsearch_status-master/public/app.js
Module not found: Error: Cannot resolve 'file' or 'directory' /home/elk/kibana-4.2/src/ui/public/autoload/styles in /home/elk/kibana-4.2/installedPlugins/elasticsearch_status-master/public
@ ./installedPlugins/elasticsearch_status-master/public/app.js 13:0-29
Unhandled rejection Error: Optimizations failure.
ERROR in ./installedPlugins/elasticsearch_status-master/public/app.js
Module not found: Error: Cannot resolve 'file' or 'directory' /home/elk/kibana-4.2/src/ui/public/autoload/styles in /home/elk/kibana-4.2/installedPlugins/elasticsearch_status-master/public
@ ./installedPlugins/elasticsearch_status-master/public/app.js 13:0-29
at Object.exports.create (/home/elk/kibana-4.2/node_modules/boom/lib/index.js:21:17)
at LazyOptimizer.failedStatsToError (/home/elk/kibana-4.2/src/optimize/BaseOptimizer.js:167:17)
at Compiler. (/home/elk/kibana-4.2/src/optimize/lazy/LazyOptimizer.js:44:22)
at Compiler.applyPlugins (/home/elk/kibana-4.2/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
at Watching._done (/home/elk/kibana-4.2/node_modules/webpack/lib/Compiler.js:78:17)
at Watching. (/home/elk/kibana-4.2/node_modules/webpack/lib/Compiler.js:51:17)
at /home/elk/kibana-4.2/node_modules/webpack/lib/Compiler.js:403:12
at Compiler.next (/home/elk/kibana-4.2/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
at Compiler. (/home/elk/kibana-4.2/node_modules/webpack/lib/CachePlugin.js:40:4)
at Compiler.applyPluginsAsync (/home/elk/kibana-4.2/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
at Compiler. (/home/elk/kibana-4.2/node_modules/webpack/lib/Compiler.js:400:9)
at Compilation. (/home/elk/kibana-4.2/node_modules/webpack/lib/Compilation.js:576:13)
at Compilation.applyPluginsAsync (/home/elk/kibana-4.2/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
at Compilation. (/home/elk/kibana-4.2/node_modules/webpack/lib/Compilation.js:571:10)
at Compilation.applyPluginsAsync (/home/elk/kibana-4.2/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
at Compilation. (/home/elk/kibana-4.2/node_modules/webpack/lib/Compilation.js:566:9)

What are the errors mean? Thanks!

**Comment by spalger** [comment]
Sorry for letting this sit for so many months, but the error you are seeing is because it couldn't find the `ui/autoload/styles` dependency that was imported by `elasticsearch_status-master/public/app.js`

the `ui/autoload/styles` dependency was first made available in Kibana 5.0, and this generator has been making plugins for 5.0 for a long time.

see https://github.com/elastic/kibana/pull/5871
