### ISSUE TITLE
Error on npm run build

### ISSUE THREAD

**Issue by s101d1** [elastic/generator-kibana-plugin#42]
I run `npm run build` on generated example code and got error:

```
> my_new_plugin@0.0.0 build d:\projects\kibana-plugins\my-new-plugin
> plugin-helpers build

events.js:216
    throw new TypeError('"listener" argument must be a function');
    ^

TypeError: "listener" argument must be a function
    at _addListener (events.js:216:11)
    at DestroyableTransform.addListener (events.js:275:10)
    at DestroyableTransform.Readable.on (d:\projects\kibana-plugins\my-new-plugin\node_modules\readable-stream\lib\_stream_readable.js:6
67:33)
    at build (d:\projects\kibana-plugins\my-new-plugin\node_modules\@elastic\plugin-helpers\tasks\build\build_action.js:83:8)
    at main (d:\projects\kibana-plugins\my-new-plugin\node_modules\@elastic\plugin-helpers\tasks\build\build_action.js:21:7)
    at module.exports (d:\projects\kibana-plugins\my-new-plugin\node_modules\@elastic\plugin-helpers\tasks\build\build_action.js:86:3)
    at Command.<anonymous> (d:\projects\kibana-plugins\my-new-plugin\node_modules\@elastic\plugin-helpers\lib\run.js:8:12)
    at Command.listener (d:\projects\kibana-plugins\my-new-plugin\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
"run" "build"
npm ERR! node v6.9.2
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! my_new_plugin@0.0.0 build: `plugin-helpers build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my_new_plugin@0.0.0 build script 'plugin-helpers build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my_new_plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     plugin-helpers build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my_new_plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls my_new_plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     d:\projects\kibana-plugins\my-new-plugin\npm-debug.log
```

Running `npm start` is fine though. Both node.js and npm are already using the latest stable version.

Any solution for this?

**Comment by vincejin** [comment]
I had the same issue but with my custom plugin.  Updated to plugin-helpers 5.2.0 and the problem went away.

**Comment by s101d1** [comment]
I changed it to `"@elastic/plugin-helpers": "5.2.0"`, still got same error.

update:
nevermind, I forgot to run `npm update`. So thanks, it works now.

**Comment by sscarduzio** [comment]
If this is the fix, would you like a pull request?

**Comment by vincejin** [comment]
editing the package.json to 5.2.0 alone does not upgrade the plugin-helpers.  Upgrade it properly with npm:
npm update @elastic/plugin-helpers

**Comment by sscarduzio** [comment]
This is still broken and I had to browse to this issue to solve it. Again.

**Comment by spalger** [comment]
@sscarduzio can you please file an issue at https://github.com/elastic/kibana-plugin-helpers/issues/new with details about what's going on?
