### ISSUE TITLE
Failed to create a plugin

### ISSUE THREAD

**Issue by ghost** [elastic/generator-kibana-plugin#54]
Hi, I would like to create a plugin ...for that i referred this following link: https://www.timroes.de/2015/12/02/writing-kibana-4-plugins-basics/
when i created package.json and index.json files in /home/sraha/kibana/plugins/farya
i am getting these errors:

restarting server  due to changes in "plugins/farya/package.json"
server    log   [13:37:55.524] [warning][plugins] Skipping non-plugin directory at /home/farya/kibana/plugins/farya
server    log   [13:37:57.135] [info][optimize] Optimizing and caching bundles for sraha, kibana, stateSessionStorageRedirect, timelion, sense-tests and status_page. This may take a few minutes
server    log   [13:38:46.128] [info][optimize] Optimization of bundles for sraha, kibana, stateSessionStorageRedirect, timelion, sense-tests and status_page complete in 48.99 seconds
server    log   [13:38:46.226] [info][status][plugin:kibana@6.0.0-alpha3] Status changed from uninitialized to green - Ready
server    log   [13:38:46.352] [info][status][plugin:elasticsearch@6.0.0-alpha3] Status changed from uninitialized to yellow - Waiting for Elasticsearch
server    log   [13:38:46.394] [info][status][plugin:sraha@6.0.0] Status changed from uninitialized to green - Ready
server    log   [13:38:46.423] [warning] You're running Kibana 6.0.0-alpha3 with some different versions of Elasticsearch. Update Kibana or Elasticsearch to the same version to prevent compatibility issues: v6.0.0-alpha1 @ 192.168.1.69:9200 (192.168.1.69) 
server    log   [13:38:46.426] [info][status][plugin:console@6.0.0-alpha3] Status changed from uninitialized to green - Ready
server    log   [13:38:46.455] [info][status][plugin:elasticsearch@6.0.0-alpha3] Status changed from yellow to green - Kibana index ready
server    log   [13:38:46.465] [info][status][plugin:metrics@6.0.0-alpha3] Status changed from uninitialized to green - Ready
server    log   [13:38:46.906] [info][status][plugin:timelion@6.0.0-alpha3] Status changed from uninitialized to green - Ready
server    log   [13:38:46.916] [info][listening] Server running at https://192.168.1.69:5603
server    log   [13:38:46.918] [info][status][ui settings] Status changed from uninitialized to green - Ready
 restarting server  due to changes in "plugins/farya/index.js"
server    log   [13:38:56.399] [fatal] SyntaxError: /home/farya/kibana/plugins/farya/index.js: Unexpected token (6:0)
  4 |     //   });
  5 |     //   };
> 6 | 
    | ^
    at Parser.pp$5.raise (/home/farya/kibana/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/farya/kibana/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseIdentifier (/home/farya/kibana/node_modules/babylon/lib/index.js:4332:10)
    at Parser.pp$3.parsePropertyName (/home/farya/kibana/node_modules/babylon/lib/index.js:4156:96)
    at Parser.parsePropertyName (/home/farya/kibana/node_modules/babylon/lib/index.js:6145:23)
    at Parser.pp$3.parseObj (/home/farya/kibana/node_modules/babylon/lib/index.js:4045:12)
    at Parser.pp$3.parseExprAtom (/home/farya/kibana/node_modules/babylon/lib/index.js:3719:19)
    at Parser.parseExprAtom (/home/farya/kibana/node_modules/babylon/lib/index.js:7154:22)
    at Parser.pp$3.parseExprSubscripts (/home/farya/kibana/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/home/farya/kibana/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/home/farya/kibana/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/home/farya/kibana/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/home/farya/kibana/node_modules/babylon/lib/index.js:3344:19)
    at Parser.parseMaybeAssign (/home/farya/kibana/node_modules/babylon/lib/index.js:6390:20)
    at Parser.pp$3.parseExprListItem (/home/farya/kibana/node_modules/babylon/lib/index.js:4312:16)
    at Parser.parseExprListItem (/home/farya/kibana/node_modules/babylon/lib/index.js:6046:29)
FATAL { SyntaxError: /home/farya/kibana/plugins/farya/index.js: Unexpected token (6:0)
  4 |     //   });
  5 |     //   };
> 6 | 
    | ^
    at Parser.pp$5.raise (/home/farya/kibana/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/farya/kibana/node_modules/babylon/lib/index.js:1761:8)

**Comment by w33ble** [comment]
This looks like a simple syntax problem. The server was running, then you changed and saved `plugins/farya/index.js`, and then got that error. Are you sure the code is valid? Can you share what you have in that file?

**Comment by ghost** [comment]
index.js :module.exports = function(kibana) {
  return new kibana.Plugin({
    // Your plugin configuration
  });
};
I reffered this link:https://www.timroes.de/2015/12/02/writing-kibana-4-plugins-basics/

**Comment by w33ble** [comment]
```js
module.exports = function(kibana) {
  return new kibana.Plugin({
    // Your plugin configuration
  });
};
```

That's valid. I'd recommend you use es6 exports, but this will work. That's not what's in the error output though. There, the last 2 lines appear to be commented out.

```
4 | // });
5 | // };
6 |
| ^
```

**Comment by ghost** [comment]
I removed the comments and tried ..but now i got this kind of error  {"statusCode":404,"error":"Not Found"}

**Comment by w33ble** [comment]
Any chance you have this code up somewhere, maybe as a repo on github or something? It's hard to provide help without any context, I have no idea what route you're trying to use here.

**Comment by ghost** [comment]
i dont hink we have any repo on this, we get these all files created when we run "yo kibana-plugin"

**Comment by w33ble** [comment]
I'm guessing you're trying to make edits though, and running into problems. The generator should work out of the box, and it does for me. The generator was legitimately broken for a time, but it should be functional as of generator-kibana-plugin@^7.0.0. If I could see what you are writing, I could help figure out why things aren't working.

**Comment by w33ble** [comment]
Closed for lack of feedback
