### ISSUE TITLE
failed to run kibana

### ISSUE THREAD

**Issue by ghost** [elastic/generator-kibana-plugin#56]
Hi, while runnig kibana i got this error, can anyone please help me to overcome this issue

FATAL { ValidationError: child "pkg" fails because [child "buildNum" fails because ["buildNum" must be a number], child "buildSha" fails because ["buildSha" is not allowed to be empty]]
    at Object.exports.process (/home/farya/kibana.org/node_modules/joi/lib/errors.js:181:19)
    at _validateWithOptions (/home/farya/kibana.org/node_modules/joi/lib/any.js:651:31)
    at root.validate (/home/farya/kibana.org/node_modules/joi/lib/index.js:121:23)
    at Config._commit (/home/farya/kibana.org/src/server/config/config.js:101:25)
    at Config.set (/home/farya/kibana.org/src/server/config/config.js:69:10)
    at Config.extendSchema (/home/farya/kibana.org/src/server/config/config.js:42:10)
    at _lodash2.default.each.child (/home/farya/kibana.org/src/server/config/config.js:31:14)
    at arrayEach (/home/farya/kibana.org/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/home/farya/kibana.org/node_modules/lodash/index.js:3345:13)
    at Config.extendSchema (/home/farya/kibana.org/src/server/config/config.js:30:16)
    at new Config (/home/farya/kibana.org/src/server/config/config.js:21:10)
    at Function.withDefaultSchema (/home/farya/kibana.org/src/server/config/config.js:14:12)
    at KbnServer.exports.default (/home/farya/kibana.org/src/server/config/setup.js:6:29)
    at /home/farya/kibana.org/src/server/kbn_server.js:98:16
    at next (native)
    at step (/home/farya/kibana.org/src/server/kbn_server.js:81:191)
  isJoi: true,
  name: 'ValidationError',
  details: 
   [ { message: '"buildNum" must be a number',
       path: 'pkg.buildNum',
       type: 'number.base',
       context: [Object] },
     { message: '"buildSha" is not allowed to be empty',
       path: 'pkg.buildSha',
       type: 'any.empty',
       context: [Object] } ],
  _object: { pkg: { version: '0.0.0', buildNum: NaN, buildSha: '' } },
  annotate: [Function] }

**Comment by w33ble** [comment]
> FATAL { ValidationError: child "pkg" fails because [child "buildNum" fails because ["buildNum" must be a number], child "buildSha" fails because ["buildSha" is not allowed to be empty]]

Sounds like maybe your `package.json` is missing some fields. Did you create a build, and how are you running things?

**Comment by w33ble** [comment]
Closed for lack of feedback
